import Link from "next/link";
import { Breadcrumbs } from "./Breadcrumbs";
import { Shell } from "./Shell";
import { items, pathFor, recipes, recipeDisplayName, slugifyId, visibleRecipes } from "@/lib/content";
import type { Locale } from "@/lib/types";

type Faq = [string, string];
const urls = {
  battery: "https://steamcommunity.com/app/4369130/discussions/0/581678762348010261/?l=english",
  batterien: "https://steamcommunity.com/app/4369130/discussions/0/581679037480610856/?l=english",
  harvester: "https://steamcommunity.com/app/4369130/discussions/0/581679037480546005/?l=english",
  hydro: "https://steamcommunity.com/app/4369130/discussions/0/581679037480476600/?l=english",
  snow1: "https://steamcommunity.com/app/4369130/discussions/0/581679037480534743/?l=english",
  snow2: "https://steamcommunity.com/app/4369130/discussions/0/581679037480525745/?l=english",
  summit: "https://steamcommunity.com/app/4369130/discussions/0/581679037480487144/?l=english",
};
function faqLd(faq: Faq[]) { return { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }; }
function Report({ locale, children, sources, germanSource = false }: { locale: Locale; children: React.ReactNode; sources: Array<[string, string]>; germanSource?: boolean }) {
  const de = locale === "de";
  return <div className="community-report"><strong>{de ? "Berichte aus der Community" : "Community reports"}</strong><p className="community-prefix">{de ? `Von Spielern in den Steam-Foren berichtet:${germanSource ? " Einer der verlinkten Ausgangsposts ist deutsch, die übrigen sind englisch." : " Die verlinkten Ausgangsposts sind englisch."}` : "Reported by players on the Steam forums:"}</p>{children}<p className="community-sources">{sources.map(([label, url], index) => <span key={url}>{index > 0 && " · "}<a href={url}>{label} ↗</a></span>)}</p></div>;
}
function GuideShell({ locale, title, faq, children }: { locale: Locale; title: string; faq: Faq[]; children: React.ReactNode }) {
  return <Shell locale={locale}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd(faq)) }}/><Breadcrumbs locale={locale} items={[{ name: "Guides" }, { name: title }]}/><article>{children}</article></Shell>;
}
function RelatedGuides({ locale, current }: { locale: Locale; current: string }) {
  const de = locale === "de";
  const links = [
    ["battery", de ? "Batterie herstellen" : "Battery crafting"],
    ["auto-harvester", de ? "Auto Harvester" : "Auto Harvester"],
    ["snow-mountain", de ? "Schneeberg" : "Snow Mountain"],
  ].filter(([slug]) => slug !== current);
  return <section className="section-group"><h2>{de ? "Weitere Guides" : "Related guides"}</h2><p>{links.map(([slug, label], index) => <span key={slug}>{index > 0 && " · "}<Link href={pathFor(locale, `/guides/${slug}`)}>{label}</Link></span>)} · <Link href={pathFor(locale, "/quests")}>{de ? "Aufgaben" : "Quests"}</Link> · <Link href={pathFor(locale, "/recipes")}>{de ? "Rezepte" : "Recipes"}</Link></p></section>;
}

export function BatteryGuide({ locale }: { locale: Locale }) {
  const de = locale === "de";
  const batteryRecipes = recipes.filter((recipe) => /battery/i.test(`${recipe.id} ${recipe.displayName?.en ?? ""} ${recipe.displayName?.de ?? ""}`));
  const batteryItemIds = items.filter((item) => /battery/i.test(`${item.id} ${item.name?.en ?? ""} ${item.name?.de ?? ""}`)).map((item) => item.id);
  const batteryUses = recipes.filter((recipe) => recipe.inputs.some((input) => batteryItemIds.includes(input.itemId) || /battery/i.test(`${input.itemId} ${input.name?.en ?? ""} ${input.name?.de ?? ""}`)));
  const faq: Faq[] = de ? [["Wo stellt man Batterien her?", "Spieler berichten, dass Batterien nur an der Electric Press hergestellt werden."], ["Kann man Batterien am PC kaufen?", "Spieler berichten, dass Batterien nicht am PC gekauft werden können."], ["Enthalten die Demo-Daten ein Batterie-Rezept?", batteryRecipes.length ? "Ja. Die Rezeptdaten enthalten ein Batterie-Rezept." : "Nein. Die Daten des Demo-Builds enthalten kein Batterie-Rezept."]] : [["Where do you craft batteries?", "Players report that batteries can only be crafted at the Electric Press."], ["Can batteries be bought from the PC?", "Players report that batteries cannot be purchased from the PC."], ["Do the demo data files contain a battery recipe?", batteryRecipes.length ? "Yes. The recipe data contains a battery recipe." : "No. The demo's data files do not contain a battery recipe."]];
  return <GuideShell locale={locale} title={de ? "Batterie" : "Battery"} faq={faq}><header className="hero"><h1>{de ? "Chop Chop Inc. Batterie – wo sie hergestellt wird" : "Chop Chop Inc Battery - Where to Craft It"}</h1><Report locale={locale} sources={[["Battery?", urls.battery], ["Batterien", urls.batterien]]} germanSource><p className="lead">{de ? "Batterien können nur an der Electric Press hergestellt werden. Sie können nicht am PC gekauft und nicht an einer Werkbank hergestellt werden." : "Batteries can only be crafted at the Electric Press. They cannot be bought from the PC, and they cannot be made at a workbench."}</p></Report></header>
  <section className="section-group"><h2>{de ? "Wo eine Batterie hergestellt wird" : "Where to Craft a Battery"}</h2><Report locale={locale} sources={[["Battery?", urls.battery], ["Batterien", urls.batterien]]} germanSource><ul><li>{de ? "Batterien werden an der Electric Press hergestellt, die auch Electronics Press genannt wird. Sie können nicht am PC gekauft werden." : "Batteries are crafted at the Electric Press (also called the Electronics Press). They cannot be purchased from the PC."}</li><li>{de ? "Der Bauplan der Electric Press stammt aus der Fish-Aufgabenkette." : "The Electric Press blueprint comes from the Fish questline."}</li><li>{de ? "Spieler berichten, dass Aufgaben rund um die Enten fortgesetzt und Harold nach dem Bau des Aufzugs erneut besucht werden muss, bevor der Bauplan verfügbar wird." : "Players report needing to progress the duck-related quests and to revisit Harold after building the elevator before the blueprint becomes available."}</li></ul></Report></section>
  <section className="section-group"><h2>{de ? "Batterie-Rezept" : "Battery Recipe"}</h2>{batteryRecipes.length ? <RecipeTable locale={locale} rows={batteryRecipes}/> : <p>{de ? "Die Daten des Demo-Builds enthalten kein Batterie-Rezept." : "The demo's data files do not contain a battery recipe."}</p>}</section>
  <section className="section-group"><h2>{de ? "Wofür Batterien verwendet werden" : "What Batteries Are Used For"}</h2>{batteryUses.length ? <RecipeTable locale={locale} rows={batteryUses}/> : <p>{de ? "Die Rezeptdaten des Demo-Builds enthalten keine Rezepte, die eine Batterie als Eingabe verwenden." : "The demo recipe data contains no recipe that uses a Battery as an input."}</p>}</section>
  <FaqSection locale={locale} faq={faq}/><RelatedGuides locale={locale} current="battery"/></GuideShell>;
}

export function AutoHarvesterGuide({ locale }: { locale: Locale }) {
  const de = locale === "de";
  const related = recipes.filter((recipe) => recipe.category === "houseupgrades" && /workhall/i.test(recipe.id));
  const faq: Faq[] = de ? [["Wie wird der Auto Harvester freigeschaltet?", "Spieler berichten, dass er im Lab gekauft wird."], ["Wie schnell produziert der Auto Harvester?", "Spieler berichten von einem festen Zyklus von ungefähr drei Minuten."], ["Sammeln Hydro-Upgrades schneller?", "Spieler berichten, dass die Genetech-Upgrades das Produktionsintervall nicht verkürzen."]] : [["How do you unlock the Auto Harvester?", "Players report that it is purchased from the Lab."], ["How fast does the Auto Harvester produce?", "Players report a fixed cycle of roughly three minutes."], ["Do Hydro tree upgrades speed it up?", "Players report that the Genetech upgrades do not shorten its production cycle."]];
  return <GuideShell locale={locale} title="Auto Harvester" faq={faq}><header className="hero"><h1>{de ? "Chop Chop Inc. Auto Harvester – Freischalten und verwenden" : "Chop Chop Inc Auto Harvester - How to Unlock and Use It"}</h1><Report locale={locale} sources={[["auto harvester?", urls.harvester]]}><p className="lead">{de ? "Der Auto Harvester wird durch den Kauf im Lab freigeschaltet." : "The Auto Harvester is unlocked by purchasing it from the Lab."}</p></Report></header>
  <section className="section-group"><h2>{de ? "Auto Harvester freischalten" : "How to Unlock the Auto Harvester"}</h2><Report locale={locale} sources={[["auto harvester?", urls.harvester], ["Hydro Tree Upgrades", urls.hydro]]}><ul><li>{de ? "Freischaltung durch Kauf im Lab." : "Unlocked by purchasing it from the Lab."}</li><li>{de ? "Bei der ersten Verwendung werden drei Stämme der gewünschten Holzart eingesetzt. Danach produziert die Maschine dieses Holz kostenlos." : "On first use you insert 3 logs of the wood type you want. After that it produces that wood for free."}</li><li>{de ? "Die Produktion läuft in einem festen Zyklus von ungefähr drei Minuten." : "It produces on a fixed cycle of roughly 3 minutes."}</li><li>{de ? "Hydro-Baumwachstums-Upgrades von Genetech verkürzen den Zyklus des Auto Harvesters nicht." : "Hydro tree growth upgrades from Genetech do not shorten the Auto Harvester cycle."}</li></ul></Report></section>
  <section className="section-group"><h2>{de ? "Abholung automatisieren" : "Automating Collection"}</h2><Report locale={locale} sources={[["auto harvester?", urls.harvester]]}><p>{de ? "Die Ausgabe wird nicht von selbst automatisch eingesammelt. Spieler kombinieren die Maschine mit dem Automated Button Pusher und einem Lagerbehälter in der Ecke der Workhall, um das automatische Inventar zu befüllen." : "Output is not collected automatically on its own. Players pair it with the Automated Button Pusher and a storage container in the corner of the Workhall to feed the automatic inventory."}</p></Report></section>
  <section className="section-group"><h2>{de ? "Zugehörige Maschinen" : "Related Machines"}</h2><RecipeTable locale={locale} rows={related}/><p><Link href={pathFor(locale, "/recipes/category/houseupgrades")}>{de ? "Alle Hausverbesserungs-Rezepte →" : "All house-upgrade recipes →"}</Link></p></section>
  <FaqSection locale={locale} faq={faq}/><RelatedGuides locale={locale} current="auto-harvester"/></GuideShell>;
}

export function SnowMountainGuide({ locale }: { locale: Locale }) {
  const de = locale === "de";
  const faq: Faq[] = de ? [["Wie kommt man auf dem Schneeberg weiter?", "Spieler berichten, dass zuerst die erste Gebietsaufgabe am Eisberg abgeschlossen und der Big Snowman besiegt werden muss."], ["Wo befindet sich der Big Snowman?", "Spieler verorten ihn rechts von der Angelstelle."], ["Reichen Lagerfeuer und Teleporter aus?", "Spieler berichten, dass diese beiden Schritte allein den weiteren Fortschritt nicht freischalten."]] : [["How do you progress up the Snow Mountain?", "Players report that you must complete the first Ice Mountain area quest and defeat the Big Snowman."], ["Where is the Big Snowman?", "Players report that it is to the right of the fishing spot."], ["Are the bonfire and teleporter enough?", "Players report that those two steps alone do not unlock further progress."]];
  return <GuideShell locale={locale} title={de ? "Schneeberg" : "Snow Mountain"} faq={faq}><header className="hero"><h1>{de ? "Chop Chop Inc. Schneeberg – den Gipfel erreichen" : "Chop Chop Inc Snow Mountain - How to Reach the Top"}</h1><div className="community-report community-report-notice"><strong>{de ? "Nur Berichte aus der Community" : "Community reports only"}</strong><p>{de ? "Diese Seite basiert vollständig auf Spielerberichten aus den Steam-Community-Foren. Anders als unsere Rezept- und Kartenseiten beruht sie nicht auf extrahierten Spieldaten. Die verlinkten Ausgangsposts sind englisch." : "This page is based entirely on player reports from the Steam Community forums. Unlike our recipe and map pages, it does not come from extracted game data."}</p></div><Report locale={locale} sources={[["Snow Mountain", urls.snow1], ["snow mountain", urls.snow2], ["Top of the mountain?", urls.summit]]}><p className="lead">{de ? "Spieler berichten, dass zuerst die erste Gebietsaufgabe am Eisberg abgeschlossen und der Big Snowman besiegt werden muss, bevor der weitere Aufstieg möglich ist." : "Players report you need to complete the first Ice Mountain area quest and defeat the Big Snowman before you can continue up."}</p><ul><li>{de ? "Schließe die erste Gebietsaufgabe am Eisberg ab, bevor du versuchst, weiter aufzusteigen." : "Complete the first Ice Mountain area quest before attempting to climb further."}</li><li>{de ? "Der Big Snowman befindet sich rechts von der Angelstelle. Spieler berichten, dass sie ihn mit einer Crystal Axe besiegt haben." : "The Big Snowman is located to the right of the fishing spot. Players report using a Crystal Axe to defeat it."}</li><li>{de ? "Sein Sieg bringt den Aufgabenfortschritt und die Ausrüstung, die für den weiteren Aufstieg benötigt werden." : "Defeating it yields the quest progress and equipment needed to continue upward."}</li><li>{de ? "Nur das Lagerfeuer anzuzünden und den Teleporter zu bauen reicht nicht aus." : "Lighting the bonfire and building the teleporter alone is not enough to progress."}</li><li>{de ? "Der große Baum auf dem Gipfel ist ein Story-Objekt, das mit späteren Inhalten verbunden ist." : "The large tree at the summit is a story object tied to later content."}</li></ul></Report></header><FaqSection locale={locale} faq={faq}/><RelatedGuides locale={locale} current="snow-mountain"/></GuideShell>;
}

function RecipeTable({ locale, rows }: { locale: Locale; rows: typeof recipes }) {
  const de = locale === "de";
  return <div className="coordinate-table-wrap"><table className="coordinate-table"><thead><tr><th>{de ? "Rezept" : "Recipe"}</th><th>{de ? "Materialien" : "Materials"}</th><th>{de ? "Dauer" : "Craft time"}</th></tr></thead><tbody>{rows.map((recipe) => { const name = recipeDisplayName(recipe, locale) ?? recipe.id; const hasPage = visibleRecipes.some((entry) => entry.id === recipe.id); return <tr key={recipe.id}><td>{hasPage ? <Link href={pathFor(locale, `/recipes/${slugifyId(recipe.id)}`)}>{name}</Link> : name}</td><td>{recipe.inputs.map((input) => `${input.amount ?? "—"}× ${input.name?.[locale] ?? input.itemId}`).join(", ") || "—"}</td><td>{recipe.craftTime}s</td></tr>; })}</tbody></table></div>;
}
function FaqSection({ locale, faq }: { locale: Locale; faq: Faq[] }) { const de = locale === "de"; return <section className="section-group"><h2>{de ? "Häufig gestellte Fragen" : "Frequently Asked Questions"}</h2>{faq.map(([question, answer]) => { const community = /Spieler berichten|Players report/.test(answer); return <div className={community ? "community-report" : "card"} key={question}>{community && <strong>{de ? "Berichte aus der Community" : "Community reports"}</strong>}<h3>{question}</h3><p>{answer}</p></div>; })}</section>; }
