import { Breadcrumbs } from "./Breadcrumbs";
import { Shell } from "./Shell";
import type { Locale } from "@/lib/types";

const discord="https://discord.com/invite/4wpwnxqTWg";
function FactShell({locale,title,children,faq}:{locale:Locale;title:string;children:React.ReactNode;faq?:Array<[string,string]>}){const de=locale==="de";const ld=faq?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}:null;return <Shell locale={locale}>{ld&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld)}}/>}<Breadcrumbs locale={locale} items={[{name:de?"Spielinfo":"Game Info",path:"/game-info"},{name:title}]}/><article className="legal"><h1>{title}</h1>{children}</article></Shell>}

export function PlatformsPage({locale}:{locale:Locale}){const de=locale==="de";const title=de?"Ist Chop Chop Inc. für PS5, Xbox oder Switch erhältlich?":"Is Chop Chop Inc. on PS5, Xbox or Switch?";const answer=de?"Nein. Chop Chop Inc. ist ausschließlich für PC über Steam erhältlich.":"No. Chop Chop Inc. is available only on PC through Steam.";const faq:Array<[string,string]>=de?[["Gibt es Chop Chop Inc. für PlayStation 5?","Nein. Eine PlayStation-5-Version wurde nicht angekündigt."],["Gibt es eine Xbox- oder Nintendo-Switch-Version?","Nein. Es wurde keine Konsolenversion angekündigt."],["Unterstützt Chop Chop Inc. Multiplayer oder Koop?","Nein. Das Spiel ist ausschließlich für Einzelspieler ausgelegt."]]:[["Is Chop Chop Inc. on PlayStation 5?","No. No PlayStation 5 version has been announced."],["Is Chop Chop Inc. on Xbox or Nintendo Switch?","No. No console version has been announced."],["Does Chop Chop Inc. have multiplayer or co-op?","No. It is single-player only."]];return <FactShell locale={locale} title={title} faq={faq}><p className="lead"><strong>{answer}</strong></p><div className="snapshot card">{[[de?"Plattform":"Platform","PC only, via Steam (App ID 4369130)"],["OS","Windows 10/11 64-bit"],["PlayStation 5",de?"Keine Version":"No version"],["Xbox",de?"Keine Version":"No version"],["Nintendo Switch",de?"Keine Version":"No version"],[de?"Konsolenstatus":"Console status",de?"Keine Konsolenversion angekündigt":"No console version announced"],[de?"Modus":"Mode",de?"Nur Einzelspieler, kein Multiplayer oder Koop":"Single-player only, no multiplayer or co-op"],["Steam Deck",de?"Nicht von Valve verifiziert":"Not verified by Valve"]].map(([key,value])=><div className="snapshot-row" key={key}><strong>{key}</strong><span>{value}</span></div>)}</div><p>{de?"Folge dem offiziellen Discord für spätere Ankündigungen.":"Follow the official Discord for future announcements."} <a href={discord}>Discord ↗</a></p></FactShell>}

export function LanguagesPage({locale}:{locale:Locale}){const de=locale==="de";const title=de?"Unterstützte Sprachen in Chop Chop Inc. – alle 7 Optionen":"Chop Chop Inc. Supported Languages - All 7 Options";const languages=["English","German","French","Spanish - Spain","Portuguese - Brazil","Simplified Chinese","Russian"];const faq:Array<[string,string]>=de?[["Wie viele Sprachen unterstützt Chop Chop Inc.?","Sieben Sprachen für die Benutzeroberfläche."],["Gibt es Sprachausgabe oder Untertitel?","Nein. Die Sprachunterstützung gilt nur für die Benutzeroberfläche; es gibt keine Sprachausgabe und keine Untertitel."],["Wird Türkisch, Japanisch oder Koreanisch unterstützt?","Nein. Diese Sprachen stehen nicht auf der offiziellen Liste."]]:[["How many languages does Chop Chop Inc. support?","Seven interface languages."],["Does Chop Chop Inc. have voice-over or subtitles?","No. Language support covers interface text only, with no voice-over and no subtitles."],["Does it support Turkish, Japanese or Korean?","No. Those languages are not on the official support list."]];return <FactShell locale={locale} title={title} faq={faq}><p>{de?"Das Spiel unterstützt sieben Sprachen für die Benutzeroberfläche. Es gibt keine Sprachausgabe und keine Untertitel.":"The game supports seven interface languages. It has no voice-over and no subtitles."}</p><ul className="language-list">{languages.map(language=><li key={language}>{language}</li>)}</ul><p>{de?"Türkisch, Japanisch, Koreanisch und weitere nicht aufgeführte Sprachen stehen nicht auf der offiziellen Supportliste.":"Turkish, Japanese, Korean and other unlisted languages are not on the official support list."}</p><p>{de?"Die Sprache kann in den Spieleinstellungen oder über Steam-Bibliothek → Spieleigenschaften → Sprache geändert werden.":"You can change the language in the game settings or through Steam Library → Game Properties → Language."}</p><p>{de?"Dieses Wiki ist derzeit auf English und Deutsch verfügbar.":"This wiki is currently available in English and Deutsch."}</p></FactShell>}

export function PriceDemoPage({locale}:{locale:Locale}){const de=locale==="de";const title=de?"Chop Chop Inc. Preis, kostenlose Demo & Veröffentlichung":"Chop Chop Inc. Price, Free Demo & Release Date";return <FactShell locale={locale} title={title}><div className="snapshot card">{[[de?"Preis":"Price","$12.99 USD"],[de?"Veröffentlicht":"Released",de?"7. August 2026":"August 7, 2026"],[de?"Entwickler":"Developer",de?"NullRef Entertainment (Darmstadt, Deutschland)":"NullRef Entertainment (Darmstadt, Germany)"],[de?"Publisher":"Publisher","rokaplay select"],["Demo",de?"Kostenlos auf Steam (App ID 4707740)":"Free on Steam (App ID 4707740)"],[de?"Speicher":"Storage","5 GB, SSD required"],[de?"Errungenschaften":"Achievements","21"],[de?"Steam-Funktionen":"Steam features","Steam Cloud, Family Sharing"]].map(([key,value])=><div className="snapshot-row" key={key}><strong>{key}</strong><span>{value}</span></div>)}</div><h2>{de?"Demo und Vollversion":"Demo vs Full Game"}</h2><p>{de?"Die kostenlose Demo umfasst frühe Spielinhalte. Die Vollversion enthält spätere Gebiete, Automatisierungssysteme und alle Rezepte.":"The free demo covers early-game content. The full game includes later areas, automation systems and all recipes."}</p></FactShell>}
