import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs } from "./Breadcrumbs";
import { Shell } from "./Shell";
import { cityMissionGroups, pageQuests, sideQuests } from "@/lib/quests";
import type { Quest } from "@/lib/quests";
import { pathFor } from "@/lib/content";
import type { Locale } from "@/lib/types";

const guideName = (locale: Locale) => locale === "de" ? "Guides" : "Guides";
const localized = (value: { en: string | null; de: string | null } | null | undefined, locale: Locale) => value?.[locale] ?? value?.en ?? null;
function TextWithFallback({value,locale}:{value:{en:string|null;de:string|null};locale:Locale}){const fallback=locale==="de"&&value.de===null;return <>{(fallback?value.en:value[locale])?.split("\n").map((line,index)=><span key={index}>{line}{index<((fallback?value.en:value[locale])?.split("\n").length??0)-1&&<br/>}</span>)}{fallback&&<small className="translation-missing">German translation not available in the game files</small>}</>}

function Objectives({quest,locale}:{quest:Quest;locale:Locale}){return <section><h2>{locale==="de"?"Ziele":"Objectives"}</h2><ol className="objective-list">{quest.objectives.filter(objective=>localized(objective.text,locale)).map(objective=><li key={objective.key}><TextWithFallback value={objective.text!} locale={locale}/></li>)}</ol></section>}
function Dialogue({quest,locale}:{quest:Quest;locale:Locale}){const metaIds=new Set(quest.segments.filter(segment=>segment.isMetaText).map(segment=>segment.id));const regular=quest.dialogue.filter(line=>!metaIds.has(line.segment??"Dialogue"));const meta=quest.dialogue.filter(line=>metaIds.has(line.segment??"Dialogue"));const render=(lines:Quest["dialogue"])=>{const segmentIds=[...new Set(lines.map(line=>line.segment??"Dialogue"))];return segmentIds.map(segment=><section className="dialogue-segment" key={segment}><h3>{segment}</h3>{lines.filter(line=>(line.segment??"Dialogue")===segment).sort((a,b)=>a.order-b.order).map(line=><div className={`dialogue-line ${line.speaker}`} key={line.key}><strong>{line.speaker==="player"?(locale==="de"?"Spieler":"Player"):"NPC"}</strong><p><TextWithFallback value={line.text} locale={locale}/></p></div>)}</section>)};return <><section><h2>{locale==="de"?"Dialog":"Dialogue"}</h2>{render(regular)}</section>{meta.length>0&&<section className="meta-dialogue"><h2>{quest.metaTextSectionTitle??"Developer Easter Eggs"}</h2>{render(meta)}</section>}</>}

export function QuestsIndexPage({locale}:{locale:Locale}){const de=locale==="de";return <Shell locale={locale}><Breadcrumbs locale={locale} items={[{name:guideName(locale),path:"/quests"},{name:de?"Aufgaben":"Quests"}]}/><h1>{de?"Chop Chop Inc. Aufgaben & Komplettlösungen":"Chop Chop Inc. Quests & Walkthroughs"}</h1><p className="lead">{de?"Aufgabenketten mit Zielen und Originaldialogen aus den Spieldateien.":"Quest chains with objectives and original dialogue extracted from the game files."}</p><div className="grid">{pageQuests.map(quest=><Link className="card" href={pathFor(locale,`/quests/${quest.slug}`)} key={quest.slug}><h2>{localized(quest.name,locale)}</h2><p>{quest.objectives.length} {de?"Ziele":"objectives"}</p></Link>)}<Link className="card" href={pathFor(locale,"/quests/side-quests")}><h2>{de?"Nebenaufgaben":"Side Quests"}</h2><p>{sideQuests.length} {de?"Aufgabenketten":"quest chains"}</p></Link></div></Shell>}
export function QuestPage({locale,slug}:{locale:Locale;slug:string}){const quest=pageQuests.find(item=>item.slug===slug);if(!quest)notFound();const name=localized(quest.name,locale)!;return <Shell locale={locale}><Breadcrumbs locale={locale} items={[{name:guideName(locale),path:"/quests"},{name:locale==="de"?"Aufgaben":"Quests",path:"/quests"},{name}]}/><article className="quest-page"><h1>{name}</h1><Objectives quest={quest} locale={locale}/><Dialogue quest={quest} locale={locale}/><p className="source-note">Dialogue extracted directly from the game files.</p></article></Shell>}
export function SideQuestsPage({locale}:{locale:Locale}){const de=locale==="de";return <Shell locale={locale}><Breadcrumbs locale={locale} items={[{name:guideName(locale),path:"/quests"},{name:de?"Nebenaufgaben":"Side Quests"}]}/><h1>{de?"Chop Chop Inc. Nebenaufgaben":"Chop Chop Inc. Side Quests"}</h1>{sideQuests.map(quest=><section className="side-quest card" key={quest.slug}><h2>{quest.slug.replace(/-/g," ").replace(/\b\w/g,letter=>letter.toUpperCase())}</h2><ol className="objective-list">{quest.objectives.filter(objective=>localized(objective.text,locale)).map(objective=><li key={objective.key}><TextWithFallback value={objective.text!} locale={locale}/></li>)}</ol></section>)}<p className="source-note">Dialogue extracted directly from the game files.</p></Shell>}
export function CityMissionsPage({locale}:{locale:Locale}){const de=locale==="de";return <Shell locale={locale}><Breadcrumbs locale={locale} items={[{name:guideName(locale),path:"/quests"},{name:de?"Stadtmissionen":"City Missions"}]}/><h1>{de?"Chop Chop Inc. Stadtmissionen":"Chop Chop Inc. City Missions"}</h1><p className="lead">{de?"Aufträge des Mission Boards, nach Zielgruppe geordnet.":"Mission Board jobs grouped by target audience."}</p>{cityMissionGroups.map(group=><section className="mission-group" key={group.targetAudience}><h2>{group.targetAudience}</h2><div className="grid">{group.missions.map(mission=>{const name=localized(mission.name??mission.text,locale);const description=mission.description?localized(mission.description,locale):null;return name?<article className="card" key={mission.key}><h3>{name}</h3>{description&&<p className="prose muted">{description}</p>}{mission.timer&&<small>{localized(mission.timer,locale)}</small>}</article>:null})}</div></section>)}</Shell>}
